repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: lint-commit-msg
        name: Lint commit message
        entry: .git/hooks/format-commit-msg.sh
        args: [.git/COMMIT_EDITMSG]
        language: script
        types: [executable]
        pass_filenames: false
        stages: [commit-msg]
        verbose: true
